# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'houghCircles.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.contrastSlider = QtWidgets.QSlider(self.centralwidget)
        self.contrastSlider.setGeometry(QtCore.QRect(150, 500, 160, 22))
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 500, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 420, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 460, 47, 16))
        self.label_2.setObjectName("label_2")
        self.radiusSlider = QtWidgets.QSlider(self.centralwidget)
        self.radiusSlider.setGeometry(QtCore.QRect(150, 420, 160, 22))
        self.radiusSlider.setOrientation(QtCore.Qt.Horizontal)
        self.radiusSlider.setObjectName("radiusSlider")
        self.minDistSlider = QtWidgets.QSlider(self.centralwidget)
        self.minDistSlider.setGeometry(QtCore.QRect(150, 460, 160, 22))
        self.minDistSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minDistSlider.setObjectName("minDistSlider")
        self.VideoFeed = QtWidgets.QLabel(self.centralwidget)
        self.VideoFeed.setGeometry(QtCore.QRect(20, 10, 731, 381))
        self.VideoFeed.setAutoFillBackground(False)
        self.VideoFeed.setText("")
        self.VideoFeed.setObjectName("VideoFeed")
        self.browseFile = QtWidgets.QPushButton(self.centralwidget)
        self.browseFile.setGeometry(QtCore.QRect(540, 500, 75, 23))
        self.browseFile.setObjectName("browseFile")
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setGeometry(QtCore.QRect(540, 450, 75, 23))
        self.stopBtn.setObjectName("stopBtn")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(540, 420, 75, 23))
        self.startBtn.setObjectName("startBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Contrast"))
        self.label.setText(_translate("MainWindow", "Radius"))
        self.label_2.setText(_translate("MainWindow", "MinDist"))
        self.browseFile.setText(_translate("MainWindow", "Browse file"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
